version: 2

references:
  container_config: &common_config
    docker:
      - image: 682250509414.dkr.ecr.eu-west-1.amazonaws.com/soldr/aws-tools:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

jobs:
  build:
    <<: *common_config
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build and push container to endpoint
          command: |
            ./_sagemaker/build_and_push.sh autocategorization
      - run: 
          name: Package cloud formation stack
          command: |
            aws cloudformation package --template serverless-sagemaker-orchestration/cloudformation/continuous_sagemaker.serverless.yaml --s3-bucket sagemaker-autocategorization > serverless-sagemaker-orchestration/cloudformation/continuous_sagemaker.serverless.yaml.package
      - run: 
          name: Deploy cloud formation stack
          command: |
            aws cloudformation deploy --stack-name autocategorizationtest --template-file serverless-sagemaker-orchestration/cloudformation/continuous_sagemaker.serverless.yaml.package --capabilities  CAPABILITY_NAMED_IAM
