model:
  path: 'learning/trained-models/'
  doc2vec_model: 'gensim_models/doc2vec_MM_new_category_tree.model'
  train_doc2vec_model: True
  categorization_model: 'lstm-multi-categorizer-new-category-tree.model'
  model_checkpoint: False #'checkpoint.weights.e{epoch:02d}-loss{val_loss:.2f}-acc{val_acc:.2f}.hdf5'
  categorization_params:
data:
  path: 'learning/data/'
  articles: 'new_metadata_articles.json'
  target_categories: 'new_top_categories.txt'

verbose: True
