model:
  path: 'learning/trained-models/'
  doc2vec_model: 'doc2vec_MM_chinese.model'
  train_doc2vec_model: False
  categorization_model: 'lstm-multi-categorizer-larger-chinese.model'
  model_checkpoint: 'checkpoint.weights.e{epoch:02d}-loss{val_loss:.2f}-acc{val_acc:.2f}-chinese.hdf5'
  categorization_params:
    use_ner: False
data:
  path: 'learning/data/'
  articles: 'thucnews_all_articles.json'
  target_categories: 'research_top_categories_thucnews.txt'

verbose: True
