model:
  path: 'learning/trained-models/'
  doc2vec_model: 'doc2vec_MM.model'
  categorization_model: 'lstm-multi-categorizer-larger.model'
  model_checkpoint: 'checkpoint.weights.e{epoch:02d}-loss{val_loss:.2f}-acc{val_acc:.2f}.hdf5'
  categorization_params:
    use_ner: False
data:
  path: 'learning/data/'
  articles: 'articles_all_categories.json'
  target_categories: 'research_top_categories.txt' #'one_year_categories.txt'

verbose: True
