model:
  path: 'learning/trained-models/'
  vec_model:
    train: False
    type: 'word2vec'
    name: 'gensim_models/word2vec_MM_new_category_tree.model'
  categorization_model:
    name: 'lstm-multi-categorizer-new-category-tree.model'
    model_checkpoint: False #'checkpoint.weights.e{epoch:02d}-loss{val_loss:.2f}-acc{val_acc:.2f}.hdf5'
    use_ner: False
data:
  path: 'learning/data/'
  stop_words: 'stop_words.txt'
  articles: 'new_metadata_articles.json'
  target_categories: 'new_top_categories.txt'

verbose: True
