model:
  path: 'learning/trained-models/'
  vec_model:
    train: True
    type: 'word2vec'
    name: 'gensim_models/word2vec_MM_new_category_tree.model'
  categorization_model:
    name: 'lstm-multi-categorizer-new-category-tree.model'
    type: 'blstm'
    model_checkpoint: False
    use_ner: False
data:
  path: 'learning/data/'
  stop_words: 'stop_words.txt'
  articles: 'new_metadata_articles.json'
  target_categories: 'new_top_categories.txt'

verbose: True
