model:
  path: 'learning/trained-models/'
  vec_model:
    train: True
    type: 'word2vec'
    name: 'gensim_models/word2vec_MM_new_category_tree.model'

  categorization_model:
    name: 'RYF-QPR-lstm-multi-categorizer-new-category-tree.model'
    type: 'blstm'
    model_checkpoint: 'checkpoint'
    category_level: 3
    category_hierarchical_prefix: RYF-QPR
    articles: learning/data/RYF-QPR_articles.jsonl

data:
  path: 'learning/data/'
  stop_words: 'stop_words.txt'
  articles: 'new_metadata_articles.jsonl'
  target_categories: 'new_top_categories.txt'
  min_word_count: 15 #minimum words required to make an accurate autocategorzation prediction.

verbose: True
