model:
  path: '/opt/ml/model/'
  doc2vec_model: 'doc2vec_MM.model'
  train_doc2vec_model: True
  categorization_model: 'lstm-multi-categorizer-larger.model'
  model_checkpoint: False
  categorization_params:
    use_ner: False
data:
  path: '/opt/ml/input/data/training/'
  articles: 'new_metadata_articles.json'
  target_categories: 'new_top_categories.txt'

verbose: True
