model:
  path: '/opt/ml/model/'
  vec_model:
    train: True
    type: 'word2vec'
    name: 'doc2vec_MM.model'
  categorization_model:
    name: 'lstm-multi-categorizer-larger.model'
    type: 'blstm'
    model_checkpoint: False #'checkpoint.weights.e{epoch:02d}-loss{val_loss:.2f}-acc{val_acc:.2f}.hdf5'
    use_ner: False
data:
  path: '/opt/ml/input/data/training/'
  articles: 'new_metadata_articles.json'
  target_categories: 'new_top_categories.txt'

verbose: False
